#+TITLE: Notes
#+AUTHOR: Maksymilian Jodłowski

* Technologies wishlist
** Backend
- Phoenix framework
- Postgres
- GraphQL - Absinthe
- Authentication - Pow?

** Frontend
- React (SPA app)
- Vite
- Bulma
- Apollo

** Deployment
- Heroku
- Docker

* Day 1
** DONE Setup repo & project skeleton
#+begin_src shell
mix phx.new employee_reward_app --no-assets --binary-id
#+end_src
** DONE Use gitflow
- Remove master branch.
- Set develop as the main branch.
- Start working on features
** DONE Integrate Phoenix with Vite/React
Based on https://moroz.dev/blog/integrating-vite-js-with-phoenix-1-6

Instead of npm or yarn I'm using pnpm.
* Day 2
** DONE Deploy to heroku
Guide used: https://hexdocs.pm/phoenix/heroku.html
Deployed to: https://secret-dawn-99555.herokuapp.com/
* Day 3
** DONE Test ueberauth.
Ueberauth seems a bit annoying to use.
Test Pow tomorrow.
* Day 4
** DONE Test Pow
Done setting up Pow
Additionally Redis is now required.
Mailer used is Mailgun.
** DONE Setup Pow Assent
Did setup with github
** DONE Setup absinthe
Just install with playground and create example endpoint
** KILL Pow and absinthe integration
Too complex
