CREATE MATERIALIZED VIEW transactions_balance AS
WITH CURRENT_ACTIVE_TRANSACTIONS AS
	 (SELECT TO_USER_ID,
			FROM_USER_ID,
			AMOUNT
		FROM TRANSACTIONS
		WHERE 
	 EXTRACT(YEAR FROM INSERTED_AT) = EXTRACT(YEAR FROM NOW()) 
	 AND 
	 EXTRACT(MONTH FROM INSERTED_AT) = EXTRACT(MONTH FROM NOW())
	 ),																																					
	RECEIVED AS
	(SELECT TO_USER_ID AS USER_ID,
			SUM(AMOUNT) AS RECEIVED
		FROM CURRENT_ACTIVE_TRANSACTIONS
		GROUP BY TO_USER_ID),
	SENT AS
	(SELECT FROM_USER_ID AS USER_ID,
			SUM(AMOUNT) AS SENT
		FROM CURRENT_ACTIVE_TRANSACTIONS
		GROUP BY FROM_USER_ID),
	PRE_BALANCE AS
	(SELECT COALESCE(R.USER_ID, S.USER_ID) USER_ID,
			COALESCE(RECEIVED,
				0) RECEIVED,
			COALESCE(SENT,
				0) SENT
		FROM RECEIVED R
		FULL OUTER JOIN SENT S ON R.USER_ID = S.USER_ID)
SELECT USER_ID,
	RECEIVED,
	SENT,
	50 - SENT + RECEIVED AS BALANCE
FROM PRE_BALANCE;