WITH RECEIVED AS
	(SELECT TO_USER_ID AS USER_ID,
			SUM(AMOUNT) AS RECEIVED,
			EXTRACT(YEAR
											FROM INSERTED_AT)::int AS YEAR,
			EXTRACT(MONTH
											FROM INSERTED_AT)::int AS MONTH
		FROM TRANSACTIONS
		WHERE STATUS = 'active'
		GROUP BY TO_USER_ID,
			YEAR,
			MONTH,
			STATUS),
	SENT AS
	(SELECT FROM_USER_ID AS USER_ID,
			SUM(AMOUNT) AS SENT,
			EXTRACT(YEAR
											FROM INSERTED_AT)::int AS YEAR,
			EXTRACT(MONTH
											FROM INSERTED_AT)::int AS MONTH
		FROM TRANSACTIONS
		WHERE STATUS = 'active'
		GROUP BY FROM_USER_ID,
			YEAR,
			MONTH,
			STATUS),
	PRE_BALANCE AS
	(SELECT COALESCE(R.USER_ID,

										S.USER_ID) USER_ID,
			COALESCE(RECEIVED,
				0) RECEIVED,
			COALESCE(SENT,
				0) SENT,
			COALESCE(R.YEAR,

				S.YEAR)::int AS YEAR,
			COALESCE(R.MONTH,

				S.MONTH) AS MONTH
		FROM RECEIVED R
		FULL OUTER JOIN SENT S ON R.USER_ID = S.USER_ID)
SELECT USER_ID,
	RECEIVED,
	SENT,
	50 - SENT + RECEIVED AS BALANCE,
	MAKE_DATE("year",

		"month", 1) YEAR_MONTH
FROM PRE_BALANCE;