SELECT FROM_USER_ID AS USER_ID,
	SUM(AMOUNT) AS SENT,
	EXTRACT(YEAR
									FROM INSERTED_AT) AS YEAR,
	EXTRACT(MONTH
									FROM INSERTED_AT) AS MONTH,
	STATUS
FROM TRANSACTIONS
GROUP BY FROM_USER_ID,
	YEAR,
	MONTH,
	STATUS;